SET SCHEMA JESSEG;

-- Create the function if it doesn't exist
CREATE OR REPLACE FUNCTION JESSEG.THREESAT()
RETURNS TABLE (
    CNF_FORMULA VARCHAR(32000)
)
LANGUAGE SQL
BEGIN
    -- Example: Return a sample 3SAT instance
    RETURN SELECT 'p cnf 3 3
1 2 -3 0
-1 2 3 0
1 -2 3 0' AS CNF_FORMULA
    FROM SYSIBM.SYSDUMMY1;
END;

SELECT * FROM TABLE(JESSEG.THREESAT()) AS t